 name: Plugin
 main: de.darkdevs.cp.main.Main
 version: 1.0.0
 description: Dies ist ein Community Plugin
 author: DarkDevs
 authors: [naix, Skillkiller, Front.]
 website:

 database: false
 depend: []

 commands:
     münzen:
         description: Schau dir dein Vermögen an